---
image_prefix: docker.io/openshift/origin-
image_version: latest
logging_use_ops: False
master_url: "https://kubernetes.default.svc.{{ openshift.common.dns_domain }}"
public_master_url: "https://{{openshift.common.public_hostname}}:8443"
logging_namespace: logging
etcd_generated_certs_dir: /etc/etcd/generated_certs
install_logging: True

curator_default_days: 30
curator_run_hour: 0
curator_run_minute: 0
curator_run_timezone: UTC
curator_script_log_level: INFO
curator_log_level: ERROR

kibana_hostname: kibana.example.com
kibana_ops_hostname: kibana-ops.example.com
kibana_proxy_debug: false

fluentd_nodeselector: '"logging-infra-fluentd": "true"'
fluentd_cpu_limit: 100m
fluentd_es_copy: False
fluentd_use_journal: False
journal_read_from_head: False
fluentd_hosts: ['--all']

es_host: logging-es
es_port: 9200
es_ca: /etc/fluent/keys/ca
es_client_cert: /etc/fluent/keys/cert
es_client_key: /etc/fluent/keys/key
es_cluster_size: 1
es_instance_ram: 1024M
es_pv_selector: None
es_pvc_dynamic: False
es_pvc_size: ""
es_pvc_prefix: logging-es
es_recover_after_time: 5m
es_storage_group: 65534

# allow cluster-admin or cluster-reader to view operations index
es_ops_allow_cluster_reader: False

es_ops_host: logging-es-ops
es_ops_port: 9200
es_ops_ca: /etc/fluent/keys/ca
es_ops_client_cert: /etc/fluent/keys/cert
es_ops_client_key: /etc/fluent/keys/key
es_ops_cluster_size: 0
es_ops_instance_ram: 1024M
es_ops_pv_selector: None
es_ops_pvc_dynamic: False
es_ops_pvc_size: ""
es_ops_pvc_prefix: logging-es-ops
es_ops_recover_after_time: 5m
es_ops_storage_group: 65534

ops_host: logging-es-ops
ops_port: 9200
ops_client_cert: /etc/fluent/keys/cert
ops_client_key: /etc/fluent/keys/key
ops_ca: /etc/fluent/keys/ca
